### ISSUE TITLE
is there a posibility that the code works on a non touch tft spi?

### ISSUE THREAD

**Issue by Thomas1305** [fowlerk/ESP8266-Color-Weather-Station-v17#1]
i mean a easy workaround, basicly for the first steps setting up the touch tft.
afterwards it should work

**Comment by Thomas1305** [comment]
lol
I think i got i.
just comment out line 573 //  checkTouchCalibration();

**Comment by fowlerk** [comment]
So, did that work?  The only issue that comes to mind is that you won’t be able to initiate config mode without a touchscreen (other than the initial setup).  You’ll miss out on a couple of features like the status screen, and the ability to turn on/off the WiFi signal strength indicator, but I really haven’t tested this otherwise to see what futher issues this may cause...

**Comment by Thomas1305** [comment]
it´s not really working. it has a lot of disadvantages like forcast is not switching, it can not display ä ö ü if i set in to german and probably a few more 
:-(

**Comment by fowlerk** [comment]
Sorry about your luck @Thomas1305...as you have discovered, the code was not designed for a non-touchscreen display.  That said, I may keep this in mind as a future enhancement.  With regard to the extended character set and translations for other languages, the character set used comes from Daniel Eichorn’s (squix78) font generator, which I don’t believe generates display fonts for extended characters.  I’m sure this could be done as an extension, but I don’t have the time to look into it now.  The translation from Open Weather Map for other languages is also quite limited, as I believe it only impacts the description of the current weather condition.
